# Build settings
markdown:            kramdown
url:                 http://japhon.github.io
author:              Japhon
author_zh:           庄泽帆
email:               sysu.zhuang@gmail.com
duoshuo:             japhon
github:              japhon
weibo:               zhuangzefan
#highlighter:         pygments
safe:                true
title:               Japhon

twitter_username:    japhonZ
github_username:     japhon

search:              true

#path
tags_path:           /tags/