# Build settings
markdown: kramdown

#markdown: rdiscount
#permalink: /blog/:year/:month/:day/:title.html
url: http://japhon.github.io
author: japhon
email: sysu.zhuang@gmail.com
duoshuo: japhon
github: japhon
weibo: zhuangzefan
highlighter: pygments
safe: true

twitter_username: japhonZ
github_username:  japhon

search: true
